### ISSUE TITLE
scrollItemAt produces a wrong behaviour (visible middle of 2 cells)

### ISSUE THREAD

**Issue by vincenzo-favara** [Oni-zerone/CollectionLayouts#19] opened 2019-09-05 09:03 UTC
I created a controller with collectionview that uses the Stories layout and I programamtically scrollItemAt and index > 0, the behaviour is that the visualized rect is in the middle between previous item I want to scroll and the target one.

**To Reproduce**
1. Add `self.collectionView.scrollToItem(at: IndexPath(item: self.index, section: 0), at: [.centeredHorizontally], animated: false)` to the `layoutSubviews()`

**Expected behavior**
Item at index should be the only visible

**Screenshots**
![IMG_1544](https://user-images.githubusercontent.com/48917328/64327744-813c4700-cfcc-11e9-912b-2a1dad452a44.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone6S
 - OS: iOS12.4

**Comment by vincenzo-favara** [comment] 2019-09-05 09:59
Actually I just fond a workaround, but I don't like it:

```
override func layoutSubviews() {
        super.layoutSubviews()
        
        if let item = self.collectionView.layoutAttributesForItem(at: IndexPath(item: self.index, section: 0)), self.index > 0 {
            var rect = item.frame
            rect.origin.x += (rect.size.width / 2)
            
            if rect.origin.x.truncatingRemainder(dividingBy: rect.size.width) == 0 {
                self.collectionView.scrollRectToVisible(rect, animated: false)
            }
        }
    }
```

**Comment by Oni-zerone** [comment] 2019-09-06 13:52
Hi @vincenzo-favara I've reproduced the bug and investigating about a valid solution, I'll work on it in this weekend.

**Comment by Oni-zerone** [comment] 2019-09-19 13:12
Hi @vincenzo-favara, sorry if I'm late on this. Definetly this one doesn't look like a good solution, but the bug looks like something in UICollectionView and not related with the layout. 
I've tried to debug this problem several times and it asks for the position of the elements, who are returned in the right way, but after that it puts the UICollectionView for a wrong contentOffset.
My suggestion for a definitive solution on this problem is to use instead the `setContentOffset:`
Here an extension who solves your problem 😉 
```swift

extension UICollectionView {
    
    func showCenteredItem(at indexPath: IndexPath, animated: Bool) {
        guard let itemAttributes = self.collectionViewLayout.layoutAttributesForItem(at: indexPath) else { return }
        self.setContentOffset(CGPoint(x: itemAttributes.center.x - (itemAttributes.bounds.width / 2),
                                      y: itemAttributes.center.y - (itemAttributes.bounds.height / 2)),
                              animated: animated)
    }
}
```
I'll wait your answer to close this issue 😊

**Closed as completed** 2019-09-21 10:55 UTC
Labels: bug, wontfix

**Comment by vincenzo-favara** [comment] 2019-10-23 10:36
Hi @Oni-zerone 

Sorry for my loong late message, but I went ahead with my job, I just adopt now your code, It works nice! thank you so much for the support

**Comment by Oni-zerone** [comment] 2019-10-23 13:01
@vincenzo-favara You welcome :D
